globals = {
	"BuildPiles",
	"StartGame",
	"AfterMove",
	"TailMoveError",
	"TailAppendError",
	"TailTapped",
	"PileTapped",
	"Complete",
	"Wikipedia",
	"CardColors",
	"Packs",

	"NewCell", "Cells",
	"NewFoundation", "Foundations",
	"NewDiscard", "Discards",
	"NewReserve", "Reserve", "Reserves",
	"NewStock", "Stock",
	"NewTableau", "Tableaux",
	"NewWaste", "Wastes", "Waste",

	"Category",
	"First",
	"Label",
	"Len",
	"MoveCard",
	"Ordinal",
	"Owner",
	"Peek",
	"Push",
	"Recycles",
	"SetCompareFunction",
	"SetLabel",
	"SetBoundary",
	"SetRecycles",
	"Toast",
	"Extract", "Bury", "Disinter",
	"FlipDown", "FlipUp",
	"DefaultTailAppendError", "DefaultTailTapped",

	"FAN_NONE",
	"FAN_RIGHT", "FAN_RIGHT3",
	"FAN_DOWN", "FAN_DOWN3",

	"MOVE_ANY",
	"MOVE_ONE", "MOVE_ONE_PLUS", "MOVE_ONE_OR_ALL",

	"CLUB", "DIAMOND", "HEART", "SPADE",
}

std = "lua51"